### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by srinivasmangipudi** [bgrayburn/meteor-processing-js#2]
Hi,
Thanks for this package. Can you please add an example where I can run a processing sketch using this package. It currently given an error saying "ReferenceError: navigator is not defined" where I run Meteor.

**Comment by clemsos** [comment]
+1

**Comment by bgrayburn** [comment]
sorry for the delay on this, just started a new job, I'll get on this asap.

**Comment by Falieson** [comment]
+1

**Comment by bgrayburn** [comment]
@srinivasmangipudi @clemsos @Falieson 
ok, updated the package to v1.0.1 and made a demo app. Link to the demo app is in the readme or [here](https://github.com/bgrayburn/meteor-processing-js-test)

let me know if there are any other problems, I'll try to be a little quicker responding ;)

**Comment by Falieson** [comment]
Thanks for putting together the demo repo.
I didn't know about P5js, thank you!

**Comment by clemsos** [comment]
cool, thx !
